Develop
imhtapm/enumerable_ruby pull request #2
Opened 2019-07-12 16:04 UTC by imhtapm

[Repl.it preview](https://repl.it/@ponmuthuselvam/enumerableruby)

2019-07-13 03:05 UTC, mcrd25 requested changes
# Wow! great attempt! Only two methods need changing! 😄  👍 

Hi @imhtapm,

Great attempt! However, some changes needed. Please address review comments and checkout following checklists.

### Concerning Project Specification Checklist

- [x] should have working my_each
- [x] should have working my_each_with_index
- [x] should have working my_select
- [x] should have working my_all? 
- [x] should have working my_none? 
- [x] should have working my_count 
- [x] should have working my_map 
- [x] should have working my_inject 


### Concerning Crucial things to make project works checklist
- [x] The project has a descriptive README.md
- [x] code is clean: indentation with two spaces, line lengths, spaces around operators. 
    (You have 4 spaces when Ruby Convention is 2 spaces)
- [x] Ensure that students work with Github Flow: main `master` branch + Pull Requests from the feature branches to the `master` (While this requirement is not met, it won't prevent you from moving on if you correct problem methods. However, you must use this flow in net project! 😄)

### Concerning Review Comments
- Address review comments and hopefully they will help you pass this project and 🚀.


*Don't forget to submit another review request for a TSE to review*

***If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media.***

**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/)

2019-07-13 03:05 UTC, mcrd25 commented on enumerable.rb
> +        self.my_each {|v| return false unless yield v}
Your code returns `false` even when it should return `true`

`my_none?` is simply the opposite of `my_any?`

This method returns true only if none of them are true so if at least one does not make it false, Which I guess you get.

However, you are returning false unless it yields true, so basically when the condition is met to return false you are skipping it. You can also get with the result of `my_any?` with `!`

*Hint 💡 : Maybe you can use and if instead.* 😃 💭

2019-07-13 03:05 UTC, mcrd25 commented on enumerable.rb
> +        self.my_each {|v| return false unless yield v}
You are essentially doing the same as `my_any?` here. It would give result for `my_any`

2019-07-13 03:05 UTC, mcrd25 commented on enumerable.rb
> +    def my_count
Your count method needs to consider for when a block is given or an argument.

so `my_count(arg = nil)` would be a great start. In case when an argument is passed the count only increases when argument = element for that particular element in array being tested.

Also please remember this method return the length of the structure if neither block or argument passed, but this is only after you have tested for a block or an argument. Which is what you already have.

This method current fails tests because of not addressing arg and blocks.

2019-07-13 07:55 UTC, imhtapm commented
I think. I used git-flow, first I developed on a feature branch, then merged to develop then only I created a pull request from develop branch to master.

2019-07-13 08:10 UTC, imhtapm commented on enumerable.rb
> +    def my_count
resolved using block_given?

2019-07-13 08:19 UTC, imhtapm commented
thank you :smile:

2019-07-13 18:34 UTC, adriaanbd requested changes
Great job, you're just missing one last case with my_count. Consider the use case when adding an argument to count, e.g. my_count(1) so that it counts the number of items that are equal to item if an argument is given.

Furthermore, please delete all of your tests, since we have our own test suite to check if your code behaves as expected, and you will be creating your own rspec tests later on.

Happy coding!

2019-07-15 05:44 UTC, AdnanAfsari approved these changes
Hello @imhtapm Congratulation 👍 

Looks good now, you can go ahead and merge the branch.

Happy Coding :)

2019-07-15 08:22 UTC, merged